workshop_title: "Mind the Gap: Opportunities and Challenges in the Transition Between Research and Industry"
workshop_date: "July 1, 2022"
workshop_date_short: "7/1/2022"
start_time: "9:00 AM"
end_time: "5:00 PM"
time_zone: "EDT"
time_zone_long: "EDT (New York Time)"
conference_name: "Robotics Science and Systems 2022"
conference_short: "RSS 2022"
conference_url: "https://roboticsconference.org"
contact_email: "bplancher@barnard.edu"
zoom_link: "TBD"
last_updated: "April 2022"
last_updated_by_github: "plancherb1"