workshop_title: "Mind the Gap: Opportunities and Challenges in the Transition Between Research and Industry"
workshop_date: "July 1, 2022"
workshop_date_short: "7/1/2022"
start_time: "9:00 AM"
end_time: "5:00 PM"
time_zone: "EDT"
time_zone_long: "EDT (New York Time)"
conference_name: "Robotics Science and Systems 2022"
conference_short: "RSS 2022"
conference_url: "https://roboticsconference.org"
contact_email: "bplancher@barnard.edu"
zoom_link: "TBD" #https://harvard.zoom.us/j/93083278440?pwd=RHFyUE1WOHVLOVFlVU0vUXhmRHJtQT09
zoom_link_on_conference_platform: true
zoom_link_on_conference_platform_instructions: "through the [conference platform](https://pheedloop.com/RSS2022/virtual/)" # You can join virtually...
physical_location: "SINDEBAND EAST 414 Room in the [CEPSR Building](https://www.facilities.columbia.edu/building-information/1066) (Go to 116th and Broadway and enter via the main Columbia Campus)"
map: 
  use_map: true
  path: "/assets/map.pdf"
last_updated: "June 2022"
last_updated_by_github: "plancherb1"